// Wit.ai
const WIT_URL = ''
if (WIT_URL) ;

// Bittrex
const BITTREX_URL = 'https://bittrex.com'

const BITTREX_NEW_MARKET_UPDATE_INTERVAL = 5 * 60 * 1000 // 5 minutes

// Facebook Messenger
const FB_SEND_API = 'https://graph.facebook.com/v2.6/me/messages'

const FB_WEBHOOK_SUB_URL = '/facebook_webhook'

const FB_EVENT_TYPE = {
  MESSAGE: 'FB_MESSAGE_EVENT',
  POSTBACK: 'FB_POSTBACK_EVENT',
  EMPTY: 'EMPTY'
}

const FB_POSTBACKS = {
  BALLANCE_BUTTON_POSTBACK: 'BALANCE_BUTTON_POSTBACK',
  UPDATE_MARKETS_POSTBACK: 'UPDATE_MARKETS_POSTBACK'
}

// Firebase
const FIREBASE_AUTH_DOMAIN = 'bittrexbot.firebaseapp.com'

const FIREBASE_DATABASE_URL = 'https://bittrexbot.firebaseio.com'

const FIREBASE_DATABASE_USERS_SUB_URL = 'users/'

const FIREBASE_DATABASE_KEY_SUB_URL = 'key/'

const FIREBASE_DATABASE_SECRET_SUB_URL = 'secret/'

const FIREBASE_DATABASE_MARKETS_SUB_URL = 'markets/'

module.exports = {
  BITTREX_URL: BITTREX_URL,
  BITTREX_NEW_MARKET_UPDATE_INTERVAL: BITTREX_NEW_MARKET_UPDATE_INTERVAL,
  FB_SEND_API: FB_SEND_API,
  FB_WEBHOOK_SUB_URL: FB_WEBHOOK_SUB_URL,
  FB_EVENT_TYPE: FB_EVENT_TYPE,
  FB_POSTBACKS: FB_POSTBACKS,
  FIREBASE_AUTH_DOMAIN: FIREBASE_AUTH_DOMAIN,
  FIREBASE_DATABASE_URL: FIREBASE_DATABASE_URL,
  FIREBASE_DATABASE_USERS_SUB_URL: FIREBASE_DATABASE_USERS_SUB_URL,
  FIREBASE_DATABASE_KEY_SUB_URL: FIREBASE_DATABASE_KEY_SUB_URL,
  FIREBASE_DATABASE_SECRET_SUB_URL: FIREBASE_DATABASE_SECRET_SUB_URL,
  FIREBASE_DATABASE_MARKETS_SUB_URL: FIREBASE_DATABASE_MARKETS_SUB_URL
}
